application: sudmural
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:


- url: /.*
  script: main.py


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest  
  
env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'true' 